name: Package
on:
  pull_request_target:
    types: [closed]
jobs:
  package:
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           persist-credentials: false
      - uses: cloudve/helm-ci@master
        with:
          chart-name: galaxy-cvmfs-csi
          charts-repo: cloudve/helm-charts
          github-token: ${{ secrets.CHARTS_TOKEN }}
          charts-token: ${{ secrets.CHARTS_TOKEN }}
          github-labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          git-branch: ${{ github.event.pull_request.base.ref }}
