name: Package
on:
  pull_request_target:
    types: [closed]
jobs:
  package:
    if: github.event.pull_request.merged == true
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - name: Require a label and version bump to package and release
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "major,minor,patch"
      - uses: actions/checkout@v2
        with:
           persist-credentials: false
      - uses: cloudve/helm-ci@master
        with:
          chart-name: galaxy-cvmfs-csi
          charts-repo: cloudve/helm-charts
          github-token: ${{ secrets.CHARTS_TOKEN }}
          charts-token: ${{ secrets.CHARTS_TOKEN }}
          github-labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          git-branch: ${{ github.event.pull_request.base.ref }}
